[tools]
go = "1.24.6"
node = "latest"
pnpm = "latest"
"go:github.com/nats-io/natscli/nats" = { version = "latest", tags = "nats" }
"go:github.com/jmattheis/goverter/cmd/goverter" = { version = "v1.9.0", tags = "goverter" }

[env]
MISE_GO_SET_GOROOT= true

[tasks."go:build"]
run = "pnpm exec nx run-many -t build"

[tasks."go:tidy"]
run = "pnpm exec nx run-many -t tidy"

[tasks."go:lint"]
run = "pnpm exec nx run-many -t lint"

[tasks."go:test"]
run = "pnpm exec nx run-many -t test"

[tasks."go:convert"]
depends = "go:convert:*"

[tasks."go:convert:core-feature-application"]
depends = "go:convert:core-feature-application:*"

[tasks."go:convert:core-feature-application:dtos"]
run = "goverter gen './libs/core/feature/application/.../dto/...'"

[tasks."go:convert:core-feature-application:models"]
run = "goverter gen './libs/core/feature/application/.../model/...'"

[tasks."go:convert:core-feature-resource-rest"]
depends = "go:convert:core-feature-resource-rest:*"

[tasks."go:convert:core-feature-resource-rest:dtos"]
run = "goverter gen './libs/core/feature/resource/rest/.../dto/...'"

[tasks."go:convert:core-feature-resource-rest:models"]
run = "goverter gen './libs/core/feature/resource/rest/.../model/...'"
