[tools]
go = "1.25"
node = "latest"
pnpm = "latest"
"go:github.com/nats-io/natscli/nats" = { version = "latest", tags = "nats" }
"go:github.com/jmattheis/goverter/cmd/goverter" = { version = "v1.9.1", tags = "goverter" }
"go:github.com/99designs/gqlgen" = { version = "v0.17.78", tags = "gqlgen" }

[env]
MISE_GO_SET_GOROOT= true

[tasks."go:build"]
run = "pnpm exec nx run-many -t build"

[tasks."go:tidy"]
run = "pnpm exec nx run-many -t tidy"

[tasks."go:lint"]
run = "pnpm exec nx run-many -t lint"

[tasks."go:test"]
run = "pnpm exec nx run-many -t test"

[tasks."go:convert"]
depends = "go:convert:*"

[tasks."go:convert:model"]
run = "goverter gen './libs/core/model'"

[tasks."go:convert:handler:rest"]
run = "goverter gen './libs/core/handler/rest/dto'"
