// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package dto

import (
	common "libs/core/common"
	model2 "libs/core/model"

	uuid "github.com/google/uuid"
)

func NewApplicationConverter() ApplicationConvert {
	return &ApplicationConverter{}
}

type ApplicationConverter struct{}

func (c *ApplicationConverter) FromNewToModel(source *NewApplication, target *model2.NewApplication) {
	if source != nil {
		target.Name = source.Name
		target.Version = source.Version
	}
}
func (c *ApplicationConverter) FromUpdateToModel(source *UpdateApplication, target *model2.UpdateApplication) error {
	if source != nil {
		uuidUUID, err := uuid.Parse(source.ID)
		if err != nil {
			return err
		}
		target.ID = uuidUUID
		target.Version = source.Version
	}
	return nil
}
func (c *ApplicationConverter) ToDto(source *model2.Application, target *Application) {
	if source != nil {
		target.ID = common.UuidToString(source.ID)
		target.Name = source.Name
		target.Version = source.Version
	}
}
