// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package dto

import (
	model2 "libs/core/model"

	uuid "github.com/google/uuid"
)

func NewRouteResourceConverter() RouteResourceConvert {
	return &RouteResourceConverter{}
}

type RouteResourceConverter struct{}

func (c *RouteResourceConverter) FromNewToModel(source *NewRouteResource, target *model2.NewRouteResource) {
	if source != nil {
		target.Path = source.Path
		target.Name = source.Name
		target.Description = source.Description
	}
}
func (c *RouteResourceConverter) FromUpdateToModel(source *UpdateRouteResource, target *model2.UpdateRouteResource) error {
	if source != nil {
		uuidUUID, err := uuid.Parse(source.ID)
		if err != nil {
			return err
		}
		target.ID = uuidUUID
		target.Path = source.Path
		target.Name = source.Name
		target.Description = source.Description
	}
	return nil
}
func (c *RouteResourceConverter) ToDto(source *model2.RouteResource, target *RouteResource) {
	if source != nil {
		target.ID = c.uuidUUIDToUuidUUID(source.ID)
		target.Path = source.Path
		target.Name = source.Name
		target.Description = source.Description
	}
}
func (c *RouteResourceConverter) uuidUUIDToUuidUUID(source uuid.UUID) uuid.UUID {
	var uuidUUID uuid.UUID
	for i := 0; i < len(source); i++ {
		uuidUUID[i] = source[i]
	}
	return uuidUUID
}
