package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"
	graphql1 "libs/core/graphql/model"
)

// CreateApplication is the resolver for the createApplication field.
func (r *mutationResolver) CreateApplication(ctx context.Context, input graphql1.NewApplication) (*graphql1.Application, error) {
	panic(fmt.Errorf("not implemented: CreateApplication - createApplication"))
}

// Applications is the resolver for the applications field.
func (r *queryResolver) Applications(ctx context.Context) ([]*graphql1.Application, error) {
	panic(fmt.Errorf("not implemented: Applications - applications"))
}
