// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package model

import (
	uuid "github.com/google/uuid"
	http "libs/core/common/http"
	entity "libs/core/feature/resource/restapi/repository/entity"
)

func NewConverter() Convert {
	return &Converter{}
}

type Converter struct{}

func (c *Converter) FromNewToEntity(source *NewRestApiResource, target *entity.RestApiResource) {
	if source != nil {
		target.Path = source.Path
		target.Method = http.ToString(source.Method)
	}
}
func (c *Converter) FromUpdateToEntity(source *UpdateRestApiResource, target *entity.RestApiResource) {
	if source != nil {
		target.ID = c.uuidUUIDToUuidUUID(source.ID)
		target.Path = source.Path
		target.Method = http.ToString(source.Method)
	}
}
func (c *Converter) ToModel(source *entity.RestApiResource, target *RestApiResource) {
	if source != nil {
		target.ID = c.uuidUUIDToUuidUUID(source.ID)
		target.Path = source.Path
		target.Method = http.ToHttpMethod(source.Method)
	}
}
func (c *Converter) uuidUUIDToUuidUUID(source uuid.UUID) uuid.UUID {
	var uuidUUID uuid.UUID
	for i := 0; i < len(source); i++ {
		uuidUUID[i] = source[i]
	}
	return uuidUUID
}
