package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"
	graphql1 "libs/core/graphql/model"
)

// CreateRoute is the resolver for the createRoute field.
func (r *mutationResolver) CreateRoute(ctx context.Context, input graphql1.NewRoute) (*graphql1.Route, error) {
	panic(fmt.Errorf("not implemented: CreateRoute - createRoute"))
}

// Routes is the resolver for the routes field.
func (r *queryResolver) Routes(ctx context.Context) ([]*graphql1.Route, error) {
	panic(fmt.Errorf("not implemented: Routes - routes"))
}
