// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package mapper

import (
	uuid "github.com/google/uuid"
	entity "libs/core/feature/resource/route/entity"
	model "libs/core/feature/resource/route/model"
)

type ModelMapper struct{}

func (c *ModelMapper) FromNewToEntity(source *model.NewRoute, target *entity.Route) {
	if source != nil {
		target.Path = source.Path
		target.Name = source.Name
		target.Description = source.Description
	}
}
func (c *ModelMapper) FromUpdateToEntity(source *model.UpdateRoute, target *entity.Route) {
	if source != nil {
		target.ID = c.uuidUUIDToUuidUUID(source.ID)
		target.Path = source.Path
		target.Name = source.Name
		target.Description = source.Description
	}
}
func (c *ModelMapper) ToModel(source *entity.Route, target *model.Route) {
	if source != nil {
		target.ID = c.uuidUUIDToUuidUUID(source.ID)
		target.Path = source.Path
		target.Name = source.Name
		target.Description = source.Description
	}
}
func (c *ModelMapper) uuidUUIDToUuidUUID(source uuid.UUID) uuid.UUID {
	var uuidUUID uuid.UUID
	for i := 0; i < len(source); i++ {
		uuidUUID[i] = source[i]
	}
	return uuidUUID
}
