// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package dto

import (
	uuid "github.com/google/uuid"
	http "libs/core/common/http"
	model "libs/core/feature/resource/restapi/service/model"
)

func NewConverter() Convert {
	return &Converter{}
}

type Converter struct{}

func (c *Converter) FromNewToModel(source *NewRestApiResource, target *model.NewRestApiResource) {
	if source != nil {
		target.Path = source.Path
		target.Method = http.ToHttpMethod(source.Method)
	}
}
func (c *Converter) FromUpdateToModel(source *UpdateRestApiResource, target *model.UpdateRestApiResource) error {
	if source != nil {
		uuidUUID, err := uuid.Parse(source.ID)
		if err != nil {
			return err
		}
		target.ID = uuidUUID
		target.Path = source.Path
		target.Method = http.ToHttpMethod(source.Method)
	}
	return nil
}
func (c *Converter) ToDto(source *model.RestApiResource, target *RestApiResource) {
	if source != nil {
		target.ID = c.uuidUUIDToUuidUUID(source.ID)
		target.Path = source.Path
		target.Method = http.ToString(source.Method)
	}
}
func (c *Converter) uuidUUIDToUuidUUID(source uuid.UUID) uuid.UUID {
	var uuidUUID uuid.UUID
	for i := 0; i < len(source); i++ {
		uuidUUID[i] = source[i]
	}
	return uuidUUID
}
