// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package mapper

import (
	"libs/core/feature/application/entity"
	model "libs/core/feature/application/model"

	uuid "github.com/google/uuid"
)

type ModelMapper struct{}

func (c *ModelMapper) FromNewToEntity(source *model.NewApplication, target *entity.Application) {
	if source != nil {
		target.Name = source.Name
		target.Version = source.Version
	}
}
func (c *ModelMapper) FromUpdateToEntity(source *model.UpdateApplication, target *entity.Application) {
	if source != nil {
		target.ID = c.uuidUUIDToUuidUUID(source.ID)
		target.Version = source.Version
	}
}
func (c *ModelMapper) ToModel(source *entity.Application, target *model.Application) {
	if source != nil {
		target.ID = c.uuidUUIDToUuidUUID(source.ID)
		target.Name = source.Name
		target.Version = source.Version
	}
}
func (c *ModelMapper) uuidUUIDToUuidUUID(source uuid.UUID) uuid.UUID {
	var uuidUUID uuid.UUID
	for i := 0; i < len(source); i++ {
		uuidUUID[i] = source[i]
	}
	return uuidUUID
}
