// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package mapper

import (
	uuid "github.com/google/uuid"
	common "libs/core/common"
	model "libs/core/feature/application/model"
	dto "libs/core/feature/application/rest/dto"
)

type RestDtoMapper struct{}

func (c *RestDtoMapper) FromNewToModel(source *dto.NewApplication, target *model.NewApplication) {
	if source != nil {
		target.Name = source.Name
		target.Version = source.Version
	}
}
func (c *RestDtoMapper) FromUpdateToModel(source *dto.UpdateApplication, target *model.UpdateApplication) error {
	if source != nil {
		uuidUUID, err := uuid.Parse(source.ID)
		if err != nil {
			return err
		}
		target.ID = uuidUUID
		target.Version = source.Version
	}
	return nil
}
func (c *RestDtoMapper) ToDto(source *model.Application, target *dto.Application) {
	if source != nil {
		target.ID = common.UuidToString(source.ID)
		target.Name = source.Name
		target.Version = source.Version
	}
}
