// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package model

import (
	uuid "github.com/google/uuid"
	entity "libs/core/entity"
)

func NewApplicationConverter() ApplicationConvert {
	return &ApplicationConverter{}
}

type ApplicationConverter struct{}

func (c *ApplicationConverter) FromNewToEntity(source *NewApplication, target *entity.Application) {
	if source != nil {
		target.Name = source.Name
		target.Version = source.Version
	}
}
func (c *ApplicationConverter) FromUpdateToEntity(source *UpdateApplication, target *entity.Application) {
	if source != nil {
		target.ID = c.uuidUUIDToUuidUUID(source.ID)
		target.Version = source.Version
	}
}
func (c *ApplicationConverter) ToModel(source *entity.Application, target *Application) {
	if source != nil {
		target.ID = c.uuidUUIDToUuidUUID(source.ID)
		target.Name = source.Name
		target.Version = source.Version
	}
}
func (c *ApplicationConverter) uuidUUIDToUuidUUID(source uuid.UUID) uuid.UUID {
	var uuidUUID uuid.UUID
	for i := 0; i < len(source); i++ {
		uuidUUID[i] = source[i]
	}
	return uuidUUID
}
