// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package dto

import (
	uuid "github.com/google/uuid"
	common "libs/core/common"
	model "libs/core/feature/application/service/model"
)

func NewConverter() Convert {
	return &Converter{}
}

type Converter struct{}

func (c *Converter) ToDto(source *model.Application, target *Application) {
	if source != nil {
		target.ID = common.UuidToString(source.ID)
		target.Name = source.Name
		target.Version = source.Version
	}
}
func (c *Converter) ToModelNew(source *NewApplication, target *model.NewApplication) {
	if source != nil {
		target.Name = source.Name
		target.Version = source.Version
	}
}
func (c *Converter) ToModelUpdate(source *UpdateApplication, target *model.UpdateApplication) error {
	if source != nil {
		uuidUUID, err := uuid.Parse(source.ID)
		if err != nil {
			return err
		}
		target.ID = uuidUUID
		target.Version = source.Version
	}
	return nil
}
