// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type Application struct {
	ID string `json:"id"`
}

type Mutation struct {
}

type NewApplication struct {
	Name string `json:"name"`
}

type NewRoute struct {
	Name string `json:"name"`
}

type Query struct {
}

type Route struct {
	ID string `json:"id"`
}
